/**
 * [LAYER: INFRASTRUCTURE]
 * Extended Seed Data for the DreamBeesArt Blog.
 * 
 * This file adds specialized, niche-focused series and articles.
 */

export const EXTENDED_SERIES = [
  {
    id: 'ser-5',
    title: 'The Digital Alchemist',
    slug: 'digital-alchemist',
    description: 'Mastering the fusion of traditional art theory with cutting-edge digital tools.',
    categoryIds: ['digital-art'],
    articleCount: 3,
    difficulty: 'intermediate',
    featuredImageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-6',
    title: 'TCG Economics: Predictive Modeling',
    slug: 'tcg-economics-modeling',
    description: 'Using data science and historical trends to predict the next big market shift.',
    categoryIds: ['market-analysis'],
    articleCount: 3,
    difficulty: 'advanced',
    featuredImageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-7',
    title: 'The Metadata Revolution',
    slug: 'metadata-revolution',
    description: 'How blockchain and RFID are transforming the physical card authentication landscape.',
    categoryIds: ['collecting-101'],
    articleCount: 2,
    difficulty: 'advanced',
    featuredImageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-8',
    title: 'Neuro-Aesthetics',
    slug: 'neuro-aesthetics',
    description: 'The science of how the human brain perceives card art and rarity.',
    categoryIds: ['digital-art'],
    articleCount: 2,
    difficulty: 'intermediate',
    featuredImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-9',
    title: 'The Tournament Grinder',
    slug: 'tournament-grinder-handbook',
    description: 'Hard-won lessons from the 2026 international tournament circuit.',
    categoryIds: ['tcg-strategy'],
    articleCount: 2,
    difficulty: 'advanced',
    featuredImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-10',
    title: 'The AI Artist Manifesto',
    slug: 'ai-artist-manifesto',
    description: 'Redefining authorship and ethics in the age of generative creation.',
    categoryIds: ['digital-art'],
    articleCount: 2,
    difficulty: 'intermediate',
    featuredImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const EXTENDED_POSTS = [
  // --- DIGITAL ART SERIES ---
  {
    id: 'blog-40',
    categoryId: 'digital-art',
    title: 'The Golden Ratio in Digital Composition',
    slug: 'golden-ratio-digital-composition',
    excerpt: 'Why classical mathematics is the secret weapon of the modern digital artist.',
    content: '## The Geometry of Beauty\n\nDigital art often feels "flat" because it lacks the underlying structural rigor of classical painting. We explore how to apply the Fibonacci spiral to your Procreate canvases.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 15400,
    helpfulCount: 1200,
    tags: ['art-theory', 'digital-art', 'composition'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-5',
    seriesPosition: 1
  },
  {
    id: 'blog-41',
    categoryId: 'digital-art',
    title: 'Simulating Oil Textures: The Physics of Brush Strokes',
    slug: 'simulating-oil-textures-physics',
    excerpt: 'Deep dive into custom brush settings to achieve museum-quality texture in a digital medium.',
    content: '## Beyond the Pixel\n\nThe most common critique of digital art is that it looks "too clean." We break down the forensic settings for pressure, jitter, and grain to simulate the resistance of real oil paint.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 12800,
    helpfulCount: 950,
    tags: ['technique', 'digital-painting', 'textures'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1513364238172-c8a4866258d4?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-5',
    seriesPosition: 2
  },

  // --- MARKET ANALYSIS SERIES ---
  {
    id: 'blog-42',
    categoryId: 'market-analysis',
    title: 'The Liquidity Index: Quantifying TCG Asset Health',
    slug: 'liquidity-index-tcg-health',
    excerpt: 'Why "Market Price" is a lie, and why "Liquidity" is the only metric that matters for high-stakes traders.',
    content: '## The Liquidity Trap\n\nA card might be "worth" $5,000, but if there are only 2 buyers a year, your asset is effectively illiquid. We introduce the DreamBees Liquidity Index (DBLI).',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 22000,
    helpfulCount: 1800,
    tags: ['finance', 'data', 'investing'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-6',
    seriesPosition: 1
  },
  {
    id: 'blog-43',
    categoryId: 'market-analysis',
    title: 'Sentiment Analysis: Scraping the Hype for Profit',
    slug: 'sentiment-analysis-tcg-hype',
    excerpt: 'How we use natural language processing to detect the next market spike before it hits the charts.',
    content: '## Front-Running the FOMO\n\nBy the time you see a card trending on Twitter, the profit has already been made. We discuss using AI to scan Discord and Reddit for early "Sentiment Shift" signals.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 19500,
    helpfulCount: 1400,
    tags: ['ai', 'market-watch', 'trading'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-6',
    seriesPosition: 2
  },

  // --- FGC STRATEGY ---
  {
    id: 'blog-44',
    categoryId: 'fgc-strategy',
    title: 'Frame Data Forensic: The Science of the "Wiff Punish"',
    slug: 'frame-data-forensic-wiff-punish',
    excerpt: 'Breaking down the 60fps reality of high-level fighting game competition.',
    content: '## The 16ms Decision\n\nIn competitive Street Fighter and Tekken, the game is won in the gaps. We analyze the mathematical window of a "Wiff Punish" and how to train your muscle memory for frame-perfect execution.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 28000,
    helpfulCount: 2200,
    tags: ['fgc', 'frames', 'esports'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-45',
    categoryId: 'fgc-strategy',
    title: 'The Psychology of the Mix-Up: Forcing Human Error',
    slug: 'psychology-of-the-mixup',
    excerpt: 'Why "Perfect Play" doesn\'t exist, and how to exploit the biological limitations of your opponent.',
    content: '## Conditioning the Mind\n\nA mix-up isn\'t just a 50/50 guess; it\'s a psychological setup. We discuss "Option Selects" and how to condition your opponent into making a fatal mistake.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 24500,
    helpfulCount: 1900,
    tags: ['mindset', 'psychology', 'competition'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },

  // --- NEW TCG STRATEGY ---
  {
    id: 'blog-46',
    categoryId: 'tcg-strategy',
    title: 'Deck Archetype Archeology: Rediscovering the "Lost" Meta',
    slug: 'deck-archetype-archeology-lost-meta',
    excerpt: 'Why forgotten decklists from 2024 are suddenly dominating the 2026 professional circuit.',
    content: '## The Cyclical Nature of Power\n\nIn the TCG world, nothing truly dies. We look at how a fringe "Stall-Burn" deck from two years ago found its perfect counter-meta in the current high-velocity format.\n\n### Case Study: The Return of the Monarchs\nWe analyze why tribute summoning—once thought dead—has become the ultimate deterrent against "Special Summon" heavy decks.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 18200,
    helpfulCount: 1450,
    tags: ['history', 'meta-shift', 'yugioh'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1620336655174-3268cb1b7470?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-47',
    categoryId: 'tcg-strategy',
    title: 'The Tempo Paradox: Playing Slower for Faster Wins',
    slug: 'tempo-paradox-slower-wins',
    excerpt: 'Quantifying the value of "The Pass." When doing nothing is the most aggressive play you can make.',
    content: '## The Illusion of Action\n\nNew players feel the need to use every resource every turn. We introduce the "Conservation of Momentum" theory, proving that holding a single card for two extra turns increases your win probability by 14%.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 31000,
    helpfulCount: 2800,
    tags: ['theory', 'advanced', 'strategy'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-54',
    categoryId: 'tcg-strategy',
    title: 'Side-Decking for the Apocalypse: Winning Game 2 and 3',
    slug: 'side-decking-apocalypse-guide',
    excerpt: 'The match isn\'t won in the first 15 minutes. It\'s won in the 3 minutes of shuffling between games.',
    content: '## The Hidden Half of the Game\n\nMost players spend 90% of their testing time on Game 1. We argue that 60% of tournament wins are decided by side-deck optimization. We analyze the "Silver Bullet" theory vs. "Engine-Swapping."',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 15400,
    helpfulCount: 1200,
    tags: ['tournament', 'side-deck', 'meta'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-9',
    seriesPosition: 1
  },
  {
    id: 'blog-55',
    categoryId: 'tcg-strategy',
    title: 'The Mental Stack: Managing Cognitive Load',
    slug: 'mental-stack-cognitive-load-tcg',
    excerpt: 'How the pros maintain focus over 12 rounds of high-stakes play.',
    content: '## Fighting Brain Fog\n\nBy Round 9, your decision-making capacity drops by 30%. We discuss "Heuristic Shortcutting" and how to automate simple decisions to save your mental energy for the critical Turn 4 play.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 12800,
    helpfulCount: 950,
    tags: ['mindset', 'performance', 'health'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-9',
    seriesPosition: 2
  },

  // --- NEW COLLECTING 101 ---
  {
    id: 'blog-48',
    categoryId: 'collecting-101',
    title: 'RFID Tagging: The Final Boss of TCG Authentication',
    slug: 'rfid-tagging-authentication',
    excerpt: 'How major grading companies are using sub-surface RFID to eliminate the possibility of slab-swapping.',
    content: '## The End of the Proxy Era?\n\nBy 2026, the physical slab is no longer just plastic. We explain how "Encapsulated Identity" works and why your next PSA 10 will likely have a digital heartbeat.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 42000,
    helpfulCount: 3500,
    tags: ['tech', 'security', 'grading'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-7',
    seriesPosition: 1
  },
  {
    id: 'blog-49',
    categoryId: 'collecting-101',
    title: 'Vaulting 101: Comparing Asset Custodians',
    slug: 'vaulting-asset-custodians-comparison',
    excerpt: 'Should you keep your collection at home, or in a Swiss bunker? We audit the world\'s top TCG vaults.',
    content: '## The Custody Dilemma\n\nIf you own $500k in cards, your home insurance likely won\'t cover a flood. We compare the fee structures and forensic security protocols of the top 3 TCG custodians.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 15600,
    helpfulCount: 1100,
    tags: ['storage', 'finance', 'safety'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-7',
    seriesPosition: 2
  },
  {
    id: 'blog-56',
    categoryId: 'collecting-101',
    title: 'The Shadow Market: Navigating Discord Auctions',
    slug: 'shadow-market-discord-auctions-safety',
    excerpt: 'The best deals aren\'t on eBay. They are in private, invite-only Discord servers. Here is how to not get scammed.',
    content: '## Beyond the Public Eye\n\nHigh-value cards often change hands without ever hitting a public listing. We discuss the "Reputation Economy" and the forensic steps you must take before sending five figures to a stranger in a chat room.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 28400,
    helpfulCount: 2200,
    tags: ['buying', 'safety', 'auctions'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-57',
    categoryId: 'collecting-101',
    title: 'Grading Arbitrage: PSA vs. BGS vs. CGC in 2026',
    slug: 'grading-arbitrage-comparison-2026',
    excerpt: 'Can you really double your money by "cross-grading"? We run the numbers on 100 sample cards.',
    content: '## The Value of the Label\n\nA BGS 9.5 is often cheaper than a PSA 10, despite having better sub-grades. We analyze the market sentiment shift of 2026 and whether the "Cross-Grade" strategy is still viable.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 31500,
    helpfulCount: 2600,
    tags: ['grading', 'arbitrage', 'investment'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },

  // --- NEW CREATOR STRATEGIES ---
  {
    id: 'blog-50',
    categoryId: 'creator-strategies',
    title: 'The Ghost Writer AI: Maintaining Voice in a Post-LLM World',
    slug: 'ghost-writer-ai-maintaining-voice',
    excerpt: 'How to use AI as a collaborator without losing the "human soul" of your editorial brand.',
    content: '## The Authenticity Gap\n\nReaders can smell AI-generated fluff from a mile away. We share the DreamBees "Hybrid Prompting" workflow that allows you to scale production by 10x while keeping your unique tone.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 24000,
    helpfulCount: 1900,
    tags: ['ai', 'content-creation', 'writing'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-51',
    categoryId: 'creator-strategies',
    title: 'Collaborative Sovereignty: The Rise of Creator Co-ops',
    slug: 'collaborative-sovereignty-creator-coops',
    excerpt: 'Why 2026 is the year solo creators start banding together to fight platform fees.',
    content: '## Strength in Numbers\n\nThe era of the "Solo Entrepreneur" is evolving. We analyze three major TCG creator collectives that have successfully negotiated better rates with major marketplaces.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 12800,
    helpfulCount: 950,
    tags: ['business', 'community', 'cooperation'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-58',
    categoryId: 'creator-strategies',
    title: 'The Multi-Platform Pivot: Beyond YouTube',
    slug: 'multi-platform-pivot-strategy',
    excerpt: 'Why diversifying your traffic sources is the only way to survive the 2026 algorithm shift.',
    content: '## The Algorithmic Cliff\n\nCreators who relied 100% on YouTube saw their reach drop by 40% last quarter. We discuss the "Hub-and-Spoke" model for content distribution across decentralized platforms.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 19400,
    helpfulCount: 1400,
    tags: ['growth', 'platforms', 'survival'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-59',
    categoryId: 'creator-strategies',
    title: 'Personal Branding Forensic: The Face of Authority',
    slug: 'personal-branding-forensic-authority',
    excerpt: 'In an era of AI avatars, human vulnerability is your most valuable asset.',
    content: '## The Paradox of Perfection\n\nAI can create perfect videos, but it can\'t create "trust." We analyze why creators who show their flaws and "behind-the-scenes" struggles are seeing 3x higher conversion rates than polished brands.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 22000,
    helpfulCount: 1800,
    tags: ['branding', 'trust', 'marketing'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },

  // --- NEW DIGITAL ART ---
  {
    id: 'blog-52',
    categoryId: 'digital-art',
    title: 'The Scent of a Pixel: Neural-Link Haptics',
    slug: 'neural-link-haptics-digital-art',
    excerpt: 'Exploring the 2026 breakthrough in "Sensory Art" and how it impacts digital gallery spaces.',
    content: '## Beyond Sight and Sound\n\nWith the integration of neural haptics, digital art is no longer just visual. We discuss how artists are "composing" scents and textures to create immersive card-art experiences.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 9400,
    helpfulCount: 720,
    tags: ['tech', 'future', 'art'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-8',
    seriesPosition: 1
  },
  {
    id: 'blog-53',
    categoryId: 'digital-art',
    title: 'Neuro-Aesthetics: Why Certain Arts Sell for Millions',
    slug: 'neuro-aesthetics-art-valuation',
    excerpt: 'Mapping the brain\'s response to color theory and rarity in the TCG landscape.',
    content: '## The Dopamine of Design\n\nWhy does a specific shade of holographic foil trigger a "Buy" response? We dive into the neurological studies of 2025 that mapped eye-tracking and brain activity to card art popularity.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 22500,
    helpfulCount: 1840,
    tags: ['psychology', 'art-theory', 'market'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1513364238172-c8a4866258d4?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-8',
    seriesPosition: 2
  },
  {
    id: 'blog-60',
    categoryId: 'digital-art',
    title: 'The Death of the Prompt: Spatial Intent',
    slug: 'death-of-the-prompt-spatial-intent',
    excerpt: 'Why "Prompt Engineering" is already a legacy skill, and what comes next.',
    content: '## Moving Beyond Text\n\nThe most advanced digital artists in 2026 aren\'t typing keywords; they are using "Spatial Intent" controllers to sculpt latent space in real-time. We explore the new gestural interfaces for creative AI.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 15400,
    helpfulCount: 1100,
    tags: ['ai', 'future', 'workflow'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-10',
    seriesPosition: 1
  },
  {
    id: 'blog-61',
    categoryId: 'digital-art',
    title: 'Crypto-Pigments: Verifying Color Authenticity',
    slug: 'crypto-pigments-digital-authenticity',
    excerpt: 'How blockchain is being used to "own" specific hex codes in the fine art world.',
    content: '## The Property of Light\n\nIn 2026, you don\'t just own an image; you can own the spectral signature of the pigments used. We discuss the rise of "Crypto-Pigments" and how they are used to verify the provenance of digital masterpieces.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 8900,
    helpfulCount: 650,
    tags: ['blockchain', 'color', 'fine-art'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-10',
    seriesPosition: 2
  },

  // --- STANDALONE EXTRAS ---
  {
    id: 'blog-62',
    categoryId: 'market-analysis',
    title: 'The Whale Tracker: Analyzing Top Wallets',
    slug: 'whale-tracker-tcg-wallets-analysis',
    excerpt: 'What are the world\'s biggest TCG collectors buying right now? We analyze the movement of $100M in assets.',
    content: '## Following the Smart Money\n\nBy tracking the public addresses of the top 100 TCG investors, we can see a clear trend towards "B-Tier" vintage assets. We break down the top 5 acquisitions of the last 30 days.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 45000,
    helpfulCount: 3800,
    tags: ['market-watch', 'whales', 'data'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-63',
    categoryId: 'fgc-strategy',
    title: 'Adaptive AI Sparring: The New Pro Meta',
    slug: 'adaptive-ai-sparring-fgc-training',
    excerpt: 'Why the best fighting game players in the world are training against machines, not humans.',
    content: '## The Silicon Sparring Partner\n\nIn 2026, AI can simulate the playstyles of specific pro players with 95% accuracy. We discuss how top FGC competitors use "Adaptive AI" to download their opponents before the tournament even starts.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 19800,
    helpfulCount: 1540,
    tags: ['fgc', 'ai', 'training'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  }
];


